update on 2018-03-21 12:05:10 fix bug

diff --git a/ss-switch b/ss-switch
--- a/ss-switch
+++ b/ss-switch
@@ -2,7 +2,25 @@
 
 main_cfg='/etc/ss-tproxy.conf'
 
-while getopts ":s:p:m:k:O:o:G:g:t:" OPT; do
+function usage() {
+{
+    echo -e "\e[37mUsage:\e[0m \e[36m${0}\e[0m \e[1;37mOPTIONS\e[0m"
+    echo -e "\e[1;37mOPTIONS\e[0m := {"
+    echo -e "\t\e[33m-t\e[0m \e[33;1mtype\e[0m\t\t\tserver type {ss|ssr} \e[35;1m*\e[0m"
+    echo -e "\t\e[33m-s\e[0m \e[33;1maddr\e[0m\t\t\tserver address"
+    echo -e "\t\e[33m-p\e[0m \e[33;1mport\e[0m\t\t\tserver port"
+    echo -e "\t\e[33m-m\e[0m \e[33;1mmethod\e[0m\t\tserver method"
+    echo -e "\t\e[33m-k\e[0m \e[33;1mpasswd\e[0m\t\tserver password"
+    echo -e "\t\e[33m-O\e[0m \e[33;1mprotocol\e[0m\t\tserver protocol"
+    echo -e "\t\e[33m-G\e[0m \e[33;1mprotocol_param\e[0m\tserver protocol_param"
+    echo -e "\t\e[33m-o\e[0m \e[33;1mobfs\e[0m\t\t\tserver obfs"
+    echo -e "\t\e[33m-g\e[0m \e[33;1mobfs_param\e[0m\t\tserver obfs_param"
+    echo -e "\t\e[33m-h --help\e[0m\t\tshow current help"
+    echo -e "}"
+} | more
+}
+
+while getopts ":s:p:m:k:O:o:G:g:t:h" OPT; do
     case $OPT in
         s) addr="$OPTARG";;
         p) port="$OPTARG";;
@@ -13,7 +31,8 @@ while getopts ":s:p:m:k:O:o:G:g:t:" OPT; do
         o) obfs="$OPTARG";;
         g) obfs_param="$OPTARG";;
         t) type="$OPTARG";;
-        :) echo "missing argument to '-$OPTARG'" 1>&2; exit 1;;
+        h) usage 1>&2; exit;;
+        :) echo -e "\e[35mmissing argument to\e[0m \e[31m'-$OPTARG'\e[0m" 1>&2; usage 1>&2; exit 1;;
     esac
 done
 
@@ -36,6 +55,7 @@ elif [ "$type" = 'ssr' ]; then
     if [ -n "$obfs_param" ]; then sed -ri "s@server_obfs_param=.+@server_obfs_param='$obfs_param'@g" $main_cfg; fi
     ss-tproxy restart
 else
-    echo "invalid type '$type'" 1>&2
+    echo -e "\e[35minvalid type\e[0m \e[31m'$type'\e[0m" 1>&2
+    usage 1>&2
     exit 1
 fi
